---
title: "Daily Affect Sleep-wake Composition"
author: "Flora Le (flora.le@monash.edu)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(extraoperators)
library(compositions)
library(zCompositions)
library(multilevelcoda)
library(brms)
library(cmdstanr)
library(insight)
library(MASS)
library(bayestestR)

library(doFuture)
library(foreach)
library(parallel)
library(doRNG)
library(future)
library(multilevelTools)
library(JWileymisc)
library(bayesplot)
```


## Data scoring

```{r}
shs <- as.data.table(readRDS("/Volumes/shared/Behavioral-med-lab/StressHealthStudy/SHS Research Interns/Data/shs_daily_ggir.RDS"))
destress <- readRDS("/Volumes/shared/Behavioral-med-lab/DESTRESSStudy/Data/destress_daily_ggir.RDS")
aces <- readRDS("/Volumes/shared/Behavioral-med-lab/ACESStudy/Data/aces_daily_ggir.RDS")

parts <- c("Sleepg", "WAKEg", "MVPAg", "LPAg", "SBg")

d <- rbind(shs[, .(ID, UID = paste0("S", ID), SurveyDay, 
                   PosAffHA, PosAffLA, NegAffHA, NegAffLA,
                   PosAffHANextDay, PosAffLANextDay, NegAffHANextDay, NegAffLANextDay,
                   Sleepg, WAKEg, MVPAg, LPAg, SBg)],
           destress[, .(ID, UID = paste0("D", ID), SurveyDay, 
                        PosAffHA, PosAffLA, NegAffHA, NegAffLA,
                        PosAffHANextDay, PosAffLANextDay, NegAffHANextDay, NegAffLANextDay,
                        Sleepg, WAKEg, MVPAg, LPAg, SBg)],
           aces[, .(ID, UID = paste0("A", ID), SurveyDay,
                    PosAffHA, PosAffLA, NegAffHA, NegAffLA,
                    PosAffHANextDay, PosAffLANextDay, NegAffHANextDay, NegAffLANextDay,
                    Sleepg, WAKEg, MVPAg, LPAg, SBg)])
d <- d[complete.cases(d[, .(Sleepg, WAKEg, MVPAg, LPAg, SBg)])]

composition_imp <- lrEM(d[, parts, with = FALSE], label = 0,dl = rep(1,5), ini.cov = "multRepl")
d <- cbind(d[, -parts, with = FALSE], composition_imp)

# make composition
sbp <- matrix(c(
  1, 1, -1,-1, -1,
  1, -1, 0, 0, 0,
  0, 0, 1, -1, -1,
  0, 0, 0, 1, -1), ncol = 5, byrow = TRUE)

cilr5 <- compilr(d,
                 sbp = sbp,
                 parts = parts,
                 idvar = "UID")

psych::describe(d$Sleepg)
psych::describe(d$WAKEg)
psych::describe(d$MVPAg)
psych::describe(d$LPAg)
psych::describe(d$SBg)


```

## HAPA

```{r}
mhapa <- brmcoda(cilr5,
              PosAffHANextDay ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + PosAffHA + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)

# mhapa <- brmcoda(cilr5,
#               PosAffHA ~ bilr1 + bilr2 + bilr3 + bilr4 +
#                wilr1 + wilr2 + wilr3 + wilr4 + (1 | UID), 
#              cores = 4,
#              chains = 4,
#              iter = 3000,
#              warmup = 500,
#              seed = 123,
#              backend = "cmdstanr"
# )

summary(mhapa$Model)

registerDoFuture()
plan(multisession, workers = 5)

mhapa_sub <- substitution(
  mhapa,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "clustermean")

registerDoSEQ()

mhapa_sub <- substitution(
  mhapa,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

summary(mhapa_sub, delta = 30)

plot(mhapa_sub, to = "Sleepg", ref = "grandmean", level = "between")
plot(mhapa_sub, to = "WAKEg", ref = "grandmean", level = "between")
plot(mhapa_sub, to = "MVPAg", ref = "grandmean", level = "between")
plot(mhapa_sub, to = "LPAg", ref = "grandmean", level = "between")
plot(mhapa_sub, to = "SBg", ref = "grandmean", level = "between")

plot(mhapa_sub, to = "Sleepg", ref = "grandmean", level = "within")
plot(mhapa_sub, to = "WAKEg", ref = "grandmean", level = "within")
plot(mhapa_sub, to = "MVPAg", ref = "grandmean", level = "within")
plot(mhapa_sub, to = "LPAg", ref = "grandmean", level = "within")
plot(mhapa_sub, to = "SBg", ref = "grandmean", level = "within")

```

## LAPA

```{r}
mlapa <- brmcoda(cilr5,
              PosAffLANextDay ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + PosAffLA + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)
summary(mlapa$Model)

mlapa_sub <- substitution(
  mlapa,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

summary(mlapa_sub, delta = 30)
plot(mlapa_sub, to = "Sleepg", ref = "grandmean", level = "between")
plot(mlapa_sub, to = "WAKEg", ref = "grandmean", level = "between")
plot(mlapa_sub, to = "MVPAg", ref = "grandmean", level = "between")
plot(mlapa_sub, to = "LPAg", ref = "grandmean", level = "between")
plot(mlapa_sub, to = "SBg", ref = "grandmean", level = "between")

plot(mlapa_sub, to = "Sleepg", ref = "grandmean", level = "within")
plot(mlapa_sub, to = "WAKEg", ref = "grandmean", level = "within")
plot(mlapa_sub, to = "MVPAg", ref = "grandmean", level = "within")
plot(mlapa_sub, to = "LPAg", ref = "grandmean", level = "within")
plot(mlapa_sub, to = "SBg", ref = "grandmean", level = "within")

```

## HANA

```{r}
mhana <- brmcoda(cilr5,
              NegAffHANextDay ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + NegAffHA + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)

mhana <- brmcoda(cilr5,
              NegAffHA ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)

summary(mhana$Model)

mhana_sub <- substitution(
  mhana,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

summary(mhana_sub, delta = 30)
plot(mhana_sub, to = "Sleepg", ref = "grandmean", level = "between")
plot(mhana_sub, to = "WAKEg", ref = "grandmean", level = "between")
plot(mhana_sub, to = "MVPAg", ref = "grandmean", level = "between")
plot(mhana_sub, to = "LPAg", ref = "grandmean", level = "between")
plot(mhana_sub, to = "SBg", ref = "grandmean", level = "between")

plot(mhana_sub, to = "Sleepg", ref = "grandmean", level = "within")
plot(mhana_sub, to = "WAKEg", ref = "grandmean", level = "within")
plot(mhana_sub, to = "MVPAg", ref = "grandmean", level = "within")
plot(mhana_sub, to = "LPAg", ref = "grandmean", level = "within")
plot(mhana_sub, to = "SBg", ref = "grandmean", level = "within")

```

## LANA

```{r}
mlana <- brmcoda(cilr5,
              NegAffLANextDay ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + NegAffLA + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)
summary(mlana$Model)

mlana_sub <- substitution(
  mlana,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

summary(mlana_sub, delta = 30)
plot(mlana_sub, to = "Sleepg", ref = "grandmean", level = "between")
plot(mlana_sub, to = "WAKEg", ref = "grandmean", level = "between")
plot(mlana_sub, to = "MVPAg", ref = "grandmean", level = "between")
plot(mlana_sub, to = "LPAg", ref = "grandmean", level = "between")
plot(mlana_sub, to = "SBg", ref = "grandmean", level = "between")

plot(mlana_sub, to = "Sleepg", ref = "grandmean", level = "within")
plot(mlana_sub, to = "WAKEg", ref = "grandmean", level = "within")
plot(mlana_sub, to = "MVPAg", ref = "grandmean", level = "within")
plot(mlana_sub, to = "LPAg", ref = "grandmean", level = "within")
plot(mlana_sub, to = "SBg", ref = "grandmean", level = "within")
```

